repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.15
    hooks:
      - id: ruff
        name: ruff-astrosky
        files: ^astrosky/
        args:
          - --fix
          - --config=astrosky/pyproject.toml

      - id: ruff-format
        name: ruff-format-astrosky
        files: ^astrosky/
        args:
          - --config=astrosky/pyproject.toml

  - repo: https://github.com/PyCQA/isort
    rev: 8.0.1
    hooks:
      - id: isort
        name: isort-astrosky
        files: ^astrosky/
        args:
          - --settings-path=astrosky/pyproject.toml