[tool.poetry]
name = "astrosky-core"
version = "0.1.0"
description = "Astronomical Sky Engine"
authors = ["vitaliypopel <vitaliypopel14@gmail.com>"]

packages = [
    { include = "engine" }
]

[tool.poetry.dependencies]
python = "^3.12"
isort = "^8.0.1"
ruff = "^0.15.15"

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
multi_line_output = 3
use_parentheses = true

[tool.ruff]
format.quote-style = "single"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
