# Generated by Django 6.0.5 on 2026-06-02 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Catalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.SlugField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "catalogs",
            },
        ),
        migrations.CreateModel(
            name="Star",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.PositiveIntegerField()),
                (
                    "hip",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="Hipparcos catalog ID",
                    ),
                ),
                (
                    "hd",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="Henry Draper catalog ID",
                    ),
                ),
                (
                    "hr",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="Harvard Revised catalog ID",
                    ),
                ),
                (
                    "gl",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Gliese catalog ID"
                    ),
                ),
                (
                    "bf",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Bayer/Flamsteed catalog ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "bayer",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Bayer designation"
                    ),
                ),
                (
                    "flam",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Flamsteed number"
                    ),
                ),
                (
                    "con",
                    models.CharField(
                        max_length=3, verbose_name="Constellation abbreviation"
                    ),
                ),
                ("ra", models.FloatField(verbose_name="Right Ascension")),
                ("dec", models.FloatField(verbose_name="Declination")),
                (
                    "dist",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Distance in parsecs"
                    ),
                ),
                ("mag", models.FloatField(verbose_name="Apparent visual magnitude")),
                (
                    "absmag",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Absolute visual magnitude"
                    ),
                ),
                (
                    "spect",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Spectral type"
                    ),
                ),
                (
                    "ci",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Color index"
                    ),
                ),
                (
                    "pmra",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Right Ascension proper motion",
                    ),
                ),
                (
                    "pmdec",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Declination proper motion"
                    ),
                ),
                (
                    "rv",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Radial Velocity in km/sec"
                    ),
                ),
                (
                    "lum",
                    models.FloatField(blank=True, null=True, verbose_name="Luminosity"),
                ),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stars",
                        to="catalog.catalog",
                    ),
                ),
            ],
            options={
                "db_table": "stars",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("catalog", "source_id"), name="unique_catalog_object"
                    )
                ],
            },
        ),
    ]
