# Generated by Django 6.0.6 on 2026-06-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='IAU code')),
                ('ra', models.FloatField(verbose_name='Right Ascension')),
                ('dec', models.FloatField(verbose_name='Declination')),
                ('area', models.FloatField(verbose_name='Area in square degrees')),
                ('area_pct', models.FloatField(verbose_name='Area in percentage')),
                ('season', models.CharField(max_length=50, verbose_name='Observation season')),
                ('eq', models.CharField(max_length=50, verbose_name='Equatorial zone')),
                ('ecl', models.CharField(max_length=50, verbose_name='Ecliptic zone')),
                ('mw', models.CharField(blank=True, max_length=50, verbose_name='Milky Way zone')),
                ('quad', models.CharField(max_length=50, verbose_name='Quadrant')),
                ('origin', models.CharField(max_length=20, verbose_name='Name origin')),
            ],
            options={
                'db_table': 'constellations',
            },
        ),
    ]
