# Generated by Django 6.0.6 on 2026-06-30 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_constellation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='con',
        ),
        migrations.AddField(
            model_name='star',
            name='constellation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stars', to='catalog.constellation'),
        ),
    ]
