# Generated by Django 6.0.6 on 2026-06-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_star_con_star_constellation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='catalog',
            name='code',
            field=models.SlugField(max_length=20, unique=True, verbose_name='Catalog code'),
        ),
    ]
