# Generated by Django 6.0.6 on 2026-07-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_catalog_created_at_remove_catalog_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='star',
            name='unique_catalog_object',
        ),
        migrations.RemoveField(
            model_name='star',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='star',
            name='source_id',
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
    ]
